version: "3.9"  
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /var/run/postgresql/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - ENGINE=django.db.backends.postgresql
      - HOST=db
    command: gunicorn -w 4 -b :8000 Youtube.wsgi:application --reload
    depends_on:
      - db