# Generated by Django 4.0.4 on 2022-05-15 18:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exhausted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=128)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yt_api_keys',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'yt_channels',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'yt_queries',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('thumbnails', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'yt_videos',
            },
        ),
    ]
