# Generated by Django 4.0.4 on 2022-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
